-- MySQL Script generated by MySQL Workbench
-- Sat Jul 11 11:12:35 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema skechers_ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema skechers_ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `skechers_ecommerce` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `skechers_ecommerce` ;

-- -----------------------------------------------------
-- Table `skechers_ecommerce`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skechers_ecommerce`.`rol` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_rol_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skechers_ecommerce`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skechers_ecommerce`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(254) NOT NULL,
  `contrasena_hash` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `activo` TINYINT NOT NULL DEFAULT 1,
  `rol_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_usuario_correo` (`correo` ASC) VISIBLE,
  INDEX `fk_usuario_rol` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `skechers_ecommerce`.`rol` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skechers_ecommerce`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skechers_ecommerce`.`categoria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_categoria_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skechers_ecommerce`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skechers_ecommerce`.`producto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `precio` DECIMAL(12,2) NOT NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  `categoria_id` INT UNSIGNED NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_producto_categoria_id` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `skechers_ecommerce`.`categoria` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skechers_ecommerce`.`imagen_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skechers_ecommerce`.`imagen_producto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(500) NOT NULL,
  `orden` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `activo` TINYINT NOT NULL DEFAULT 1,
  `producto_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_imagen_producto_orden` (`producto_id` ASC, `orden` ASC) VISIBLE,
  CONSTRAINT `fk_imagen_producto_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `skechers_ecommerce`.`producto` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skechers_ecommerce`.`producto_variante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skechers_ecommerce`.`producto_variante` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `talla` VARCHAR(10) NOT NULL,
  `color` VARCHAR(50) NOT NULL,
  `sku` VARCHAR(50) NOT NULL,
  `stock` INT UNSIGNED NOT NULL DEFAULT 0,
  `activo` TINYINT NOT NULL DEFAULT 1,
  `producto_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_producto_variante_sku` (`sku` ASC) VISIBLE,
  UNIQUE INDEX `uk_producto_variante_atributos` (`producto_id` ASC, `talla` ASC, `color` ASC) VISIBLE,
  CONSTRAINT `fk_producto_variante_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `skechers_ecommerce`.`producto` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skechers_ecommerce`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skechers_ecommerce`.`carrito` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_carrito_usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `skechers_ecommerce`.`usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skechers_ecommerce`.`detalle_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skechers_ecommerce`.`detalle_carrito` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` INT UNSIGNED NOT NULL,
  `carrito_id` INT UNSIGNED NOT NULL,
  `producto_variante_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_detalle_carrito_variante` (`carrito_id` ASC, `producto_variante_id` ASC) VISIBLE,
  INDEX `fk_detalle_carrito_variante` (`producto_variante_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_carrito_carrito`
    FOREIGN KEY (`carrito_id`)
    REFERENCES `skechers_ecommerce`.`carrito` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_detalle_carrito_variante`
    FOREIGN KEY (`producto_variante_id`)
    REFERENCES `skechers_ecommerce`.`producto_variante` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skechers_ecommerce`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skechers_ecommerce`.`pedido` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE_PAGO',
  `total` DECIMAL(12,2) NOT NULL,
  `direccion_envio` VARCHAR(255) NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_pedido_usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_pedido_estado` (`estado` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `skechers_ecommerce`.`usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skechers_ecommerce`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skechers_ecommerce`.`detalle_pedido` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` INT UNSIGNED NOT NULL,
  `precio_unitario` DECIMAL(12,2) NOT NULL,
  `subtotal` DECIMAL(12,2) NOT NULL,
  `sku_producto` VARCHAR(50) NOT NULL,
  `nombre_producto` VARCHAR(150) NOT NULL,
  `talla_producto` VARCHAR(10) NOT NULL,
  `color_producto` VARCHAR(50) NOT NULL,
  `pedido_id` INT UNSIGNED NOT NULL,
  `producto_variante_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_detalle_pedido_variante` (`pedido_id` ASC, `producto_variante_id` ASC) VISIBLE,
  INDEX `fk_detalle_pedido_variante` (`producto_variante_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_pedido_pedido`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `skechers_ecommerce`.`pedido` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_detalle_pedido_variante`
    FOREIGN KEY (`producto_variante_id`)
    REFERENCES `skechers_ecommerce`.`producto_variante` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skechers_ecommerce`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skechers_ecommerce`.`pago` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `metodo_pago` VARCHAR(50) NOT NULL,
  `referencia_transaccion` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_intento` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `monto` DECIMAL(12,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  `detalle_respuesta` VARCHAR(500) NULL DEFAULT NULL,
  `pedido_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_pago_referencia_transaccion` (`referencia_transaccion` ASC) VISIBLE,
  INDEX `idx_pago_pedido_estado` (`pedido_id` ASC, `estado` ASC) VISIBLE,
  CONSTRAINT `fk_pago_pedido`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `skechers_ecommerce`.`pedido` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
